config/routes.rb
Rails.application.routes.draw do
  resources :search_songs, only: [ :index, :show, :create, :destroy ] do
    collection do
      get :search_results
      get :how_to_use
    end
    member do
      get :lyrics
    end
  end
  root "search_songs#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/search_song.rb
class SearchSong < ApplicationRecord
  validates :title, presence: true
  validates :artist_name, presence: true
  validates :url, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/search_songs_controller.rb
class SearchSongsController < ApplicationController
  before_action :set_search_song, only: %i[ show edit destroy ]

  # GET /search_songs or /search_songs.json
  def index
    @search_song = SearchSong.new
    @search_songs = SearchSong.all.order(created_at: :desc)
  end

  # GET /search_songs/search_results
  def search_results
    @search_song = SearchSong.new(search_song_params)
    if @search_song.title.present? || @search_song.artist_name.present?
      genius_client = GeniusClient.new
      @hits = genius_client.search_song(@search_song.title, @search_song.artist_name)
    else
      @hits = []
    end
  end

  def show
    @search_song = SearchSong.find(params[:id])
  end

  def lyrics
    genius_client = GeniusClient.new
    lyrics_url = params[:url]

    # URLの検証
    unless valid_url?(lyrics_url)
      flash[:alert] = "無効なURLです"
      redirect_to search_songs_path and return
    end

    @lyrics = genius_client.get_lyrics(lyrics_url)

    # デバッグ用のログ
    Rails.logger.debug "Title: #{params[:title]}"
    Rails.logger.debug "Artist Name: #{params[:artist_name]}"
    Rails.logger.debug "URL: #{params[:url]}"

    # 曲名とアーティスト名を保存
    @search_song = SearchSong.new(title: params[:title], artist_name: params[:artist_name], url: params[:url])
    if @search_song.save
      flash[:notice] = "履歴が保存されました"
    else
      flash[:alert] = "履歴の保存に失敗しました"
    end

    render :lyrics
  end

  def how_to_use
  end

  # DELETE /search_songs/1
  def destroy
    @search_song.destroy
    respond_to do |format|
      format.html { redirect_to search_songs_url, notice: "履歴を削除しました" }
      format.json { head :no_content }
    end
  end

  private

  def set_search_song
    @search_song = SearchSong.find(params[:id])
  end

  def search_song_params
    params.fetch(:search_song, {}).permit(:title, :artist_name, :url)
  end

  def valid_url?(url)
    uri = URI.parse(url)
    uri.is_a?(URI::HTTP) || uri.is_a?(URI::HTTPS)
  rescue URI::InvalidURIError
    false
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/search_songs_helper.rb
module SearchSongsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "UtaSearch" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_pack_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>
  <body class="bg-gray-100 text-gray-900">
    <div class="min-h-screen flex flex-col">
      <!-- Header -->
      <header class="bg-blue-600 text-white py-4">
        <div class="container mx-auto px-4 flex items-center justify-between">
          <h1 class="text-3xl font-bold">
            <%= link_to "UtaSearch", root_path, class: "text-white" %>
          </h1>
          <%= form_with model: @search_song, url: search_results_search_songs_path, method: :get, local: true, class: "flex items-center space-x-4" do |form| %>
            <div class="flex flex-col">
              <%= form.label :title, "Title", class: "block text-sm font-bold mb-1 text-white" %>
              <%= form.text_field :title, class: "shadow appearance-none border rounded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline w-48 h-10" %>
            </div>
            <div class="flex flex-col">
              <%= form.label :artist_name, "Artist", class: "block text-sm font-bold mb-1 text-white" %>
              <%= form.text_field :artist_name, class: "shadow appearance-none border rounded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline w-48 h-10" %>
            </div>
            <div>
              <%= form.submit "検索", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline h-10" %>
            </div>
          <% end %>
          <%= link_to "使い方", how_to_use_search_songs_path, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded ml-4" %>
        </div>
      </header>

      <!-- Main Content -->
      <main class="flex-grow container mx-auto px-4 py-8">
        <%= yield %>
      </main>

      <!-- Footer -->
      <footer class="bg-gray-800 text-white py-4">
        <div class="container mx-auto px-4 text-center">
          <p>&copy; <%= Time.now.year %> UtaSearch. All rights reserved.</p>
        </div>
      </footer>
    </div>
  </body>
</html>

app/views/search_songs/_form.html.erb
<%= form_with model: @search_song, url: search_results_search_songs_path, method: :get, local: true, class: "flex items-center space-x-4" do |form| %>
  <% if @search_song.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@search_song.errors.count, "error") %> prohibited this search_song from being saved:</h2>

      <ul>
        <% @search_song.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, "Title", class: "block text-sm font-bold mb-2 text-white" %>
    <%= form.text_field :title, class: "shadow appearance-none border rounded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>
  <div>
    <%= form.label :artist_name, "Artist", class: "block text-white text-sm font-bold mb-2" %>
    <%= form.text_field :artist_name, class: "shadow appearance-none border rounded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>
  <div>
    <%= form.submit "検索", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
  </div>
<% end %>

app/views/search_songs/_search_song.html.erb
<div id="<%= dom_id search_song %>" class="p-4 mb-4 bg-white shadow-md rounded-lg">
    <div class="flex items-center mb-2">
        <strong class="block text-gray-700 text-sm font-bold mr-2">Title:</strong>
        <p class="text-gray-900"><%= search_song.title %></p>
    </div>
    
    <div class="flex items-center mb-4">
        <strong class="block text-gray-700 text-sm font-bold mr-2">Artist:</strong>
        <p class="text-gray-900"><%= search_song.artist_name %></p>
    </div>
    
    <div class="flex space-x-2">
        <%= link_to "歌詞を見る", search_song_path(search_song), class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
        <%= button_to "歌詞を削除", search_song_path(search_song), method: :delete, class: "bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded" %>
    </div>
</div>

app/views/search_songs/edit.html.erb
<% content_for :title, "Editing search song" %>

<h1>Editing search song</h1>

<%= render "form", search_song: @search_song %>

<br>

<div>
  <%= link_to "Show this search song", @search_song %> |
  <%= link_to "Back to search songs", search_songs_path %>
</div>

app/views/search_songs/how_to_use.html.erb
<h1 class="text-2xl font-bold mb-4">アプリの使い方</h1>

<div class="bg-white shadow-md rounded-lg p-4">
  <h2 class="text-xl font-bold mb-2">検索</h2>
  <p class="mb-4">検索バーに曲のタイトルまたはアーティスト名を入力して、「検索」ボタンをクリックします。</p>

  <h2 class="text-xl font-bold mb-2">検索結果</h2>
  <p class="mb-4">検索結果が表示されます。各結果には「歌詞を見る」ボタンがあります。</p>

  <h2 class="text-xl font-bold mb-2">歌詞の表示</h2>
  <p class="mb-4">「歌詞を見る」ボタンをクリックすると、選択した曲の歌詞が表示されます。</p>

  <h2 class="text-xl font-bold mb-2">履歴の管理</h2>
  <p class="mb-4">過去に検索された曲のリストが表示されます。各曲には「歌詞を見る」ボタンと「履歴を削除」ボタンがあります。</p>
</div>

<h1 class="text-2xl font-bold mb-4 mt-5">検索のコツ</h1>
<div class="bg-white shadow-md rounded-lg p-4 mb-5">
  <p class="mb-4">曲のタイトルとアーティストのどちらか一方のみでも検索できますが、検索がヒットしない場合は両方入力してみてください。</p>
</div>
<%= link_to "戻る", root_path, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mt-4" %>

app/views/search_songs/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "歌詞一覧" %>

<h1 class="text-2xl font-bold mb-4">過去に検索された歌詞</h1>

<div id="search_songs" class="grid grid-cols-1 md:grid-cols-4 gap-4">
  <% @search_songs.each do |search_song| %>
    <div class="mb-4 p-4 bg-white shadow-md rounded-lg">
      <div class="mb-2">
        <p class="text-gray-900 mb-2"><strong class="text-gray-700 text-sm font-bold">Title:</strong> <%= search_song.title %></p>
      </div>
      <div class="mb-2">
        <p class="text-gray-900 mb-2"><strong class="text-gray-700 text-sm font-bold">Artist:</strong> <%= search_song.artist_name %></p>
      </div>
      <div class="flex space-x-2">
        <%= link_to "歌詞を見る", lyrics_search_song_path(search_song, url: search_song.url, title: search_song.title, artist_name: search_song.artist_name), class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
        <%= button_to "履歴を削除", search_song_path(search_song), method: :delete, class: "bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded" %>
      </div>
    </div>
  <% end %>
</div>

<p>
  技術検証用にミニアプリを開発しました！<br>
  曲名とアーティスト名から歌詞を検索・閲覧できるアプリです。
</p>
<br>
<p>
  ※歌詞を検索すると外部APIへのリクエストがブロックされ、エラーになります。
</p>
<p>
  対応するには月単位でコストがかかるため、本アプリでは対応しないことにしました。
</p>
<p>
  原因はPaaSを利用していることから、外部APIへのリクエスト時のIPアドレスが動的になる点と予想しています。<br>
  ローカル環境ではリクエストが成功し歌詞が取得できています。
</p>
<br>
<p>
  GitHubは公開してるので、ご興味あれば。
</p>

app/views/search_songs/lyrics.html.erb
<h1 class="text-2xl font-bold mb-4">歌詞</h1>
<%= link_to "トップに戻る", search_songs_path, class: "mb-5 bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mt-4" %>

<div class="bg-white shadow-md rounded-lg p-4 my-5">
  <pre class="whitespace-pre-wrap"><%= sanitize @lyrics %></pre>
</div>

<%= link_to "トップに戻る", search_songs_path, class: "mt-5 bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mt-4" %>

app/views/search_songs/new.html.erb
<% content_for :title, "New search song" %>

<h1>曲を探す</h1>

<%= render "form", search_song: @search_song %>

<br>

app/views/search_songs/search.html.erb
<h1 class="text-2xl font-bold mb-4">検索結果</h1>

<% if @hits.any? %>
  <ul>
    <% @hits.each do |hit| %>
      <li class="mb-4 p-4 bg-white shadow-md rounded-lg">
        <strong class="block text-gray-700 text-sm font-bold mb-2">Title:</strong>
        <p class="text-gray-900 mb-2"><%= hit["result"]["title"] %></p>
        
        <strong class="block text-gray-700 text-sm font-bold mb-2">Artist:</strong>
        <p class="text-gray-900 mb-2"><%= hit["result"]["primary_artist"]["name"] %></p>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>No results found.</p>
<% end %>

app/views/search_songs/search_results.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="text-2xl font-bold mb-4">検索結果</h1>

<div id="search_results" class="grid grid-cols-1 md:grid-cols-4 gap-4">
  <% if @hits.present? %>
    <% @hits.each do |hit| %>
      <div class="mb-4 p-4 bg-white shadow-md rounded-lg">
        <div class="mb-2">
          <p class="text-gray-900 mb-2"><strong class="text-gray-700 text-sm font-bold">Title:</strong> <%= hit["result"]["title"] %></p>
        </div>
        <div class="mb-2">
          <p class="text-gray-900 mb-2"><strong class="text-gray-700 text-sm font-bold">Artist:</strong> <%= hit["result"]["primary_artist"]["name"] %></p>
        </div>
        <div class="text-left">
          <%= link_to "歌詞を見る", lyrics_search_song_path(hit["result"]["id"], url: hit["result"]["url"], title: hit["result"]["title"], artist_name: hit["result"]["primary_artist"]["name"]), class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
        </div>
      </div>
    <% end %>
  <% else %>
    <p>No search results found.</p>
  <% end %>
</div>

app/views/search_songs/show.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="text-2xl font-bold mb-4">検索結果</h1>



<h1 class="text-2xl font-bold mb-4">曲の詳細</h1>

<div class="mb-4 p-4 bg-white shadow-md rounded-lg">
  <div class="mb-2">
    <p class="text-gray-900 mb-2"><strong class="text-gray-700 text-sm font-bold">Title:</strong> <%= @search_song.title %></p>
  </div>
  <div class="mb-2">
    <p class="text-gray-900 mb-2"><strong class="text-gray-700 text-sm font-bold">Artist:</strong> <%= @search_song.artist_name %></p>
  </div>
</div>

<%= link_to "戻る", search_songs_path, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>

<%= render @search_song %>
<%= link_to "一覧に戻る", search_songs_path, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>

<br>
<div class="mt-4">
  <pre><%= raw @lyrics %></pre>
</div>